/**
 * Configuration loading from config.json5.
 *
 * Default location: ~/.local/share/zettelkasten/config.json5
 * Override with --config <path>.
 *
 * Port defaults: 7483 (server), 7484 (checker).
 * Why 7483? ZTS on a phone keypad.
 *
 * Three config roles with different required fields:
 *   server  — all fields (runs the main server)
 *   checker — checkerPort only (runs sandboxed tests)
 *   client  — no required fields (CLI commands, agent)
 */

import JSON5 from "json5";

export const DEFAULT_DATA_DIR = `${
  Deno.env.get("HOME")
}/.local/share/zettelkasten`;
export const DEFAULT_SERVER_PORT = 7483;
export const DEFAULT_CHECKER_PORT = 7484;

export type ConfigRole = "server" | "checker" | "client";

export interface ZtsConfig {
  devToken: string;
  adminToken: string;
  serverUrl: string;
  checkerUrl: string;
  serverPort: number;
  checkerPort: number;
  embedUrl: string;
  embedModel: string;
  embedDim: number;
  dataDir: string;
}

const ROLE_REQUIRED: Record<ConfigRole, string[]> = {
  server: [
    "devToken",
    "adminToken",
    "checkerUrl",
    "serverPort",
    "checkerPort",
    "embedUrl",
    "embedModel",
    "embedDim",
  ],
  checker: ["checkerPort"],
  client: [],
};

const DEFAULT_CONFIG_TEMPLATE = `{
  // Auth tokens — generated by zts init, or: openssl rand -hex 32
  devToken: "",
  adminToken: "",

  // Server URL (for CLI/agent access)
  serverUrl: "http://localhost:${DEFAULT_SERVER_PORT}",

  // Ports (ZTS on a phone keypad)
  serverPort: ${DEFAULT_SERVER_PORT},
  checkerPort: ${DEFAULT_CHECKER_PORT},

  // Checker service URL
  checkerUrl: "http://localhost:${DEFAULT_CHECKER_PORT}",

  // Embedding service (Ollama)
  embedUrl: "http://localhost:11434/api/embeddings",
  embedModel: "nomic-embed-text",
  embedDim: 768,
}
`;

export function configPath(dataDir: string): string {
  return `${dataDir}/config.json5`;
}

export async function initConfig(dataDir: string): Promise<string> {
  const path = configPath(dataDir);

  // Refuse to overwrite existing config
  try {
    await Deno.stat(path);
    console.error(
      `error: ${path} already exists. Delete it first if you want to regenerate.`,
    );
    Deno.exit(1);
  } catch {
    // File doesn't exist — proceed
  }

  await Deno.mkdir(dataDir, { recursive: true });

  const buf = new Uint8Array(32);
  crypto.getRandomValues(buf);
  const devToken = Array.from(buf.slice(0, 16))
    .map((b) => b.toString(16).padStart(2, "0")).join("");
  crypto.getRandomValues(buf);
  const adminToken = Array.from(buf.slice(0, 16))
    .map((b) => b.toString(16).padStart(2, "0")).join("");

  const content = DEFAULT_CONFIG_TEMPLATE
    .replace('devToken: ""', `devToken: "${devToken}"`)
    .replace('adminToken: ""', `adminToken: "${adminToken}"`);

  await Deno.writeTextFile(path, content);
  await Deno.chmod(path, 0o600);

  return path;
}

export async function loadConfig(
  configFile: string,
  dataDir: string,
  role: ConfigRole,
): Promise<ZtsConfig> {
  try {
    await Deno.stat(configFile);
  } catch {
    console.error(`error: config file not found: ${configFile}`);
    console.error("  Run 'zts init' to create one.");
    Deno.exit(1);
  }

  // Check permissions — refuse if world-readable (skip in Docker)
  if (!Deno.env.get("ZTS_DOCKER")) {
    const stat = await Deno.stat(configFile);
    if (stat.mode !== null && (stat.mode & 0o077) !== 0) {
      console.error(
        `error: ${configFile} is readable by others.`,
      );
      console.error(`  Run: chmod 600 ${configFile}`);
      Deno.exit(1);
    }
  }

  const text = await Deno.readTextFile(configFile);
  let parsed: Record<string, unknown>;
  try {
    parsed = JSON5.parse(text) as Record<string, unknown>;
  } catch (e) {
    console.error(
      `error: failed to parse ${configFile}: ${(e as Error).message}`,
    );
    Deno.exit(1);
  }

  const required = ROLE_REQUIRED[role];
  const missing = required.filter((f) =>
    parsed[f] === undefined || parsed[f] === ""
  );
  if (missing.length > 0) {
    console.error(
      `error: missing or empty fields in ${configFile} (role=${role}): ${
        missing.join(", ")
      }`,
    );
    console.error(
      "  Run 'zts init' to regenerate, or add the missing fields.",
    );
    Deno.exit(1);
  }

  return {
    devToken: (parsed.devToken as string) ?? "",
    adminToken: (parsed.adminToken as string) ?? "",
    serverUrl: (parsed.serverUrl as string) ??
      `http://localhost:${parsed.serverPort ?? DEFAULT_SERVER_PORT}`,
    checkerUrl: (parsed.checkerUrl as string) ?? "",
    serverPort: (parsed.serverPort as number) ?? DEFAULT_SERVER_PORT,
    checkerPort: (parsed.checkerPort as number) ?? DEFAULT_CHECKER_PORT,
    embedUrl: (parsed.embedUrl as string) ?? "",
    embedModel: (parsed.embedModel as string) ?? "",
    embedDim: (parsed.embedDim as number) ?? 768,
    dataDir,
  };
}
